on: [push]
name: ubuntu-ci
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['8.10.2']
        cabal: ['3.4.0.0']
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
            cabal: 2.4.1.0
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: install hspec-discover
        run: |
            cabal install hspec-discover
            export PATH=$HOME/.cabal/bin:$PATH

      - run: cabal v2-build $CONFIG
      - run: cabal v2-test --test-show-details=direct
      - run: cabal v2-haddock
      - run: cabal v2-sdist
