on: [push]
name: win-ci
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['8.10.2']
        cabal: ['3.2.0.0']
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
            cabal: 2.4.1.0
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update

      - name: install hspec-discover
        run: cabal install --install-method=copy hspec-discover

      - run: cabal v2-build $CONFIG
      - run: cabal v2-test --test-show-details=direct
      - run: cabal v2-haddock
      - run: cabal v2-sdist
